name: Go Generate
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/go-generate.yaml
      - "backend/**.go"
      - backend/go.mod
      - backend/go.sum
jobs:
  go-generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.5
      - run: go install go.uber.org/mock/mockgen@latest
      - run: go generate ./...
        working-directory: backend/app
      - run: git diff --exit-code
