name: Go Test
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/go-test.yaml
      - "backend/**.go"
      - backend/app/go.mod
      - backend/app/go.sum
jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.5
          go-version-file: backend/app/go.mod
          cache-dependency-path: backend/app/go.sum
      - run: go test ./...
        working-directory: backend/app